// !!! THIS FILE IS GENERATED BY codegen.js !!!

import { SpaceProperties } from './base'

export const ma0: SpaceProperties = {
  'marginTop': 0,
  'marginRight': 0,
  'marginBottom': 0,
  'marginLeft': 0
}

export const ma1: SpaceProperties = {
  'marginTop': 6,
  'marginRight': 6,
  'marginBottom': 6,
  'marginLeft': 6
}

export const ma2: SpaceProperties = {
  'marginTop': 8,
  'marginRight': 8,
  'marginBottom': 8,
  'marginLeft': 8
}

export const ma3: SpaceProperties = {
  'marginTop': 12,
  'marginRight': 12,
  'marginBottom': 12,
  'marginLeft': 12
}

export const ma4: SpaceProperties = {
  'marginTop': 18,
  'marginRight': 18,
  'marginBottom': 18,
  'marginLeft': 18
}

export const ma5: SpaceProperties = {
  'marginTop': 24,
  'marginRight': 24,
  'marginBottom': 24,
  'marginLeft': 24
}

export const ma6: SpaceProperties = {
  'marginTop': 36,
  'marginRight': 36,
  'marginBottom': 36,
  'marginLeft': 36
}

export const ma7: SpaceProperties = {
  'marginTop': 60,
  'marginRight': 60,
  'marginBottom': 60,
  'marginLeft': 60
}

export const ma8: SpaceProperties = {
  'marginTop': 90,
  'marginRight': 90,
  'marginBottom': 90,
  'marginLeft': 90
}

export const mh0: SpaceProperties = {
  'marginLeft': 0,
  'marginRight': 0
}

export const mh1: SpaceProperties = {
  'marginLeft': 6,
  'marginRight': 6
}

export const mh2: SpaceProperties = {
  'marginLeft': 8,
  'marginRight': 8
}

export const mh3: SpaceProperties = {
  'marginLeft': 12,
  'marginRight': 12
}

export const mh4: SpaceProperties = {
  'marginLeft': 18,
  'marginRight': 18
}

export const mh5: SpaceProperties = {
  'marginLeft': 24,
  'marginRight': 24
}

export const mh6: SpaceProperties = {
  'marginLeft': 36,
  'marginRight': 36
}

export const mh7: SpaceProperties = {
  'marginLeft': 60,
  'marginRight': 60
}

export const mh8: SpaceProperties = {
  'marginLeft': 90,
  'marginRight': 90
}

export const mv0: SpaceProperties = {
  'marginTop': 0,
  'marginBottom': 0
}

export const mv1: SpaceProperties = {
  'marginTop': 6,
  'marginBottom': 6
}

export const mv2: SpaceProperties = {
  'marginTop': 8,
  'marginBottom': 8
}

export const mv3: SpaceProperties = {
  'marginTop': 12,
  'marginBottom': 12
}

export const mv4: SpaceProperties = {
  'marginTop': 18,
  'marginBottom': 18
}

export const mv5: SpaceProperties = {
  'marginTop': 24,
  'marginBottom': 24
}

export const mv6: SpaceProperties = {
  'marginTop': 36,
  'marginBottom': 36
}

export const mv7: SpaceProperties = {
  'marginTop': 60,
  'marginBottom': 60
}

export const mv8: SpaceProperties = {
  'marginTop': 90,
  'marginBottom': 90
}

export const mt0: SpaceProperties = {
  'marginTop': 0
}

export const mt1: SpaceProperties = {
  'marginTop': 6
}

export const mt2: SpaceProperties = {
  'marginTop': 8
}

export const mt3: SpaceProperties = {
  'marginTop': 12
}

export const mt4: SpaceProperties = {
  'marginTop': 18
}

export const mt5: SpaceProperties = {
  'marginTop': 24
}

export const mt6: SpaceProperties = {
  'marginTop': 36
}

export const mt7: SpaceProperties = {
  'marginTop': 60
}

export const mt8: SpaceProperties = {
  'marginTop': 90
}

export const mr0: SpaceProperties = {
  'marginRight': 0
}

export const mr1: SpaceProperties = {
  'marginRight': 6
}

export const mr2: SpaceProperties = {
  'marginRight': 8
}

export const mr3: SpaceProperties = {
  'marginRight': 12
}

export const mr4: SpaceProperties = {
  'marginRight': 18
}

export const mr5: SpaceProperties = {
  'marginRight': 24
}

export const mr6: SpaceProperties = {
  'marginRight': 36
}

export const mr7: SpaceProperties = {
  'marginRight': 60
}

export const mr8: SpaceProperties = {
  'marginRight': 90
}

export const mb0: SpaceProperties = {
  'marginBottom': 0
}

export const mb1: SpaceProperties = {
  'marginBottom': 6
}

export const mb2: SpaceProperties = {
  'marginBottom': 8
}

export const mb3: SpaceProperties = {
  'marginBottom': 12
}

export const mb4: SpaceProperties = {
  'marginBottom': 18
}

export const mb5: SpaceProperties = {
  'marginBottom': 24
}

export const mb6: SpaceProperties = {
  'marginBottom': 36
}

export const mb7: SpaceProperties = {
  'marginBottom': 60
}

export const mb8: SpaceProperties = {
  'marginBottom': 90
}

export const ml0: SpaceProperties = {
  'marginLeft': 0
}

export const ml1: SpaceProperties = {
  'marginLeft': 6
}

export const ml2: SpaceProperties = {
  'marginLeft': 8
}

export const ml3: SpaceProperties = {
  'marginLeft': 12
}

export const ml4: SpaceProperties = {
  'marginLeft': 18
}

export const ml5: SpaceProperties = {
  'marginLeft': 24
}

export const ml6: SpaceProperties = {
  'marginLeft': 36
}

export const ml7: SpaceProperties = {
  'marginLeft': 60
}

export const ml8: SpaceProperties = {
  'marginLeft': 90
}

export const pa0: SpaceProperties = {
  'paddingTop': 0,
  'paddingRight': 0,
  'paddingBottom': 0,
  'paddingLeft': 0
}

export const pa1: SpaceProperties = {
  'paddingTop': 6,
  'paddingRight': 6,
  'paddingBottom': 6,
  'paddingLeft': 6
}

export const pa2: SpaceProperties = {
  'paddingTop': 8,
  'paddingRight': 8,
  'paddingBottom': 8,
  'paddingLeft': 8
}

export const pa3: SpaceProperties = {
  'paddingTop': 12,
  'paddingRight': 12,
  'paddingBottom': 12,
  'paddingLeft': 12
}

export const pa4: SpaceProperties = {
  'paddingTop': 18,
  'paddingRight': 18,
  'paddingBottom': 18,
  'paddingLeft': 18
}

export const pa5: SpaceProperties = {
  'paddingTop': 24,
  'paddingRight': 24,
  'paddingBottom': 24,
  'paddingLeft': 24
}

export const pa6: SpaceProperties = {
  'paddingTop': 36,
  'paddingRight': 36,
  'paddingBottom': 36,
  'paddingLeft': 36
}

export const pa7: SpaceProperties = {
  'paddingTop': 60,
  'paddingRight': 60,
  'paddingBottom': 60,
  'paddingLeft': 60
}

export const pa8: SpaceProperties = {
  'paddingTop': 90,
  'paddingRight': 90,
  'paddingBottom': 90,
  'paddingLeft': 90
}

export const ph0: SpaceProperties = {
  'paddingLeft': 0,
  'paddingRight': 0
}

export const ph1: SpaceProperties = {
  'paddingLeft': 6,
  'paddingRight': 6
}

export const ph2: SpaceProperties = {
  'paddingLeft': 8,
  'paddingRight': 8
}

export const ph3: SpaceProperties = {
  'paddingLeft': 12,
  'paddingRight': 12
}

export const ph4: SpaceProperties = {
  'paddingLeft': 18,
  'paddingRight': 18
}

export const ph5: SpaceProperties = {
  'paddingLeft': 24,
  'paddingRight': 24
}

export const ph6: SpaceProperties = {
  'paddingLeft': 36,
  'paddingRight': 36
}

export const ph7: SpaceProperties = {
  'paddingLeft': 60,
  'paddingRight': 60
}

export const ph8: SpaceProperties = {
  'paddingLeft': 90,
  'paddingRight': 90
}

export const pv0: SpaceProperties = {
  'paddingTop': 0,
  'paddingBottom': 0
}

export const pv1: SpaceProperties = {
  'paddingTop': 6,
  'paddingBottom': 6
}

export const pv2: SpaceProperties = {
  'paddingTop': 8,
  'paddingBottom': 8
}

export const pv3: SpaceProperties = {
  'paddingTop': 12,
  'paddingBottom': 12
}

export const pv4: SpaceProperties = {
  'paddingTop': 18,
  'paddingBottom': 18
}

export const pv5: SpaceProperties = {
  'paddingTop': 24,
  'paddingBottom': 24
}

export const pv6: SpaceProperties = {
  'paddingTop': 36,
  'paddingBottom': 36
}

export const pv7: SpaceProperties = {
  'paddingTop': 60,
  'paddingBottom': 60
}

export const pv8: SpaceProperties = {
  'paddingTop': 90,
  'paddingBottom': 90
}

export const pt0: SpaceProperties = {
  'paddingTop': 0
}

export const pt1: SpaceProperties = {
  'paddingTop': 6
}

export const pt2: SpaceProperties = {
  'paddingTop': 8
}

export const pt3: SpaceProperties = {
  'paddingTop': 12
}

export const pt4: SpaceProperties = {
  'paddingTop': 18
}

export const pt5: SpaceProperties = {
  'paddingTop': 24
}

export const pt6: SpaceProperties = {
  'paddingTop': 36
}

export const pt7: SpaceProperties = {
  'paddingTop': 60
}

export const pt8: SpaceProperties = {
  'paddingTop': 90
}

export const pr0: SpaceProperties = {
  'paddingRight': 0
}

export const pr1: SpaceProperties = {
  'paddingRight': 6
}

export const pr2: SpaceProperties = {
  'paddingRight': 8
}

export const pr3: SpaceProperties = {
  'paddingRight': 12
}

export const pr4: SpaceProperties = {
  'paddingRight': 18
}

export const pr5: SpaceProperties = {
  'paddingRight': 24
}

export const pr6: SpaceProperties = {
  'paddingRight': 36
}

export const pr7: SpaceProperties = {
  'paddingRight': 60
}

export const pr8: SpaceProperties = {
  'paddingRight': 90
}

export const pb0: SpaceProperties = {
  'paddingBottom': 0
}

export const pb1: SpaceProperties = {
  'paddingBottom': 6
}

export const pb2: SpaceProperties = {
  'paddingBottom': 8
}

export const pb3: SpaceProperties = {
  'paddingBottom': 12
}

export const pb4: SpaceProperties = {
  'paddingBottom': 18
}

export const pb5: SpaceProperties = {
  'paddingBottom': 24
}

export const pb6: SpaceProperties = {
  'paddingBottom': 36
}

export const pb7: SpaceProperties = {
  'paddingBottom': 60
}

export const pb8: SpaceProperties = {
  'paddingBottom': 90
}

export const pl0: SpaceProperties = {
  'paddingLeft': 0
}

export const pl1: SpaceProperties = {
  'paddingLeft': 6
}

export const pl2: SpaceProperties = {
  'paddingLeft': 8
}

export const pl3: SpaceProperties = {
  'paddingLeft': 12
}

export const pl4: SpaceProperties = {
  'paddingLeft': 18
}

export const pl5: SpaceProperties = {
  'paddingLeft': 24
}

export const pl6: SpaceProperties = {
  'paddingLeft': 36
}

export const pl7: SpaceProperties = {
  'paddingLeft': 60
}

export const pl8: SpaceProperties = {
  'paddingLeft': 90
}
